development:
  nmap_path:            'nmap'
  nmap_results_path:    './data/results/nmap/%Y-%m-%d-results.nmap'
  nessus_path:          'nessus -q <host> <port> <username> <password>'
  nessus_results_path:  './data/results/nessus/%Y-%m-%d.nessus'
  nessus_plugins_path:  './data/results/nessus/%Y-%m-%d.plugins'

production:
  nmap_path:            'nmap'
  nmap_results_path:    'data/results/nmap/%Y-%m-%d-results.nmap'
  nessus_path:          'nessus -q <host> <port> <username> <password>'
  nessus_results_path:  './data/results/nessus/%Y-%m-%d.nessus'
  nessus_plugins_path:  './data/results/nessus/%Y-%m-%d.plugins'
